config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  get "/users/:id", to: "users#show"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  get "/savings/:id/index", to:"savings#index"
  resources :savings

  get '/incomes/search', to:"incomes#search"
  post '/incomes/search', to:"incomes#create"
  resources :incomes do
    collection {get "search"}
     resources :incomes, only: [ :new ]
   end

 #  get"/expends",          to:"expends#new"
 #  post "/expends",        to:"expends#create"
 #  get"/expends/new",      to:"expends#new"
 #  get "/expends/:id/edit",to:"expends#edit"
#   patch"/expends/:id",    to:"expends#update"
 #  put"/expends/:id",      to:"expends#update"
 #  delete"/expends/:id",   to:"expends#destroy"
   get '/expends/search',  to:"expends#search"
   post '/expends/search', to:"expends#create"
   resources :expends do
    collection {get "search"}
     resources :expends, only: [ :new ]
   end


 get "/analyses", to:"analyses#show"
 get '/analyses/search', to:"analyses#search"

end

app/models/expend.rb
class Expend < ApplicationRecord
    belongs_to :saving
    belongs_to :user
    
    validates :expend_amount, presence: true, length: { maximum: 100 }
    validates :saving_id, presence: true
    validates :expend_date, presence: true

    def self.search(expend_date)
        where(["expend_date", "%#{expend_date}%"])
      end
    
    def expend_date_month
      expend_date.strftime("%Y年%-m月")
    end
end

app/controllers/expends_controller.rb
class ExpendsController < ApplicationController
  before_action :authenticate_user!
 # before_action :ensure_correct_user, only: [:edit, :update, :destroy]

    def new
        @expend = Expend.new
        @expends = Expend.where(user_id:[current_user.id]).reverse_order.paginate(page:params[:page], per_page: 10)
        @expend_month = nil
        @saving_name = "口座：" +Saving.where(id:params[:id]).pluck(:saving_name).join("")
    end

    def create
        @expend = Expend.new(expend_params)
        @expend.user_id = current_user.id
        @expends = Expend.where(user_id:[current_user.id]).paginate(page:params[:page], per_page: 10)
        if @expend.save
            flash[:notice] = "成功　#{Expend.where(user_id:current_user.id).pluck(:expend_date).last.strftime("%Y年%-m月%-d日")}　#{Expend.where(user_id:current_user.id).pluck(:group).last}　￥#{Expend.where(user_id:current_user.id).pluck(:expend_amount).last}　メモ：#{Expend.where(user_id:current_user.id).pluck(:memo).last}"
          redirect_to("/expends/new")
        else
            flash.now[:alert] = "失敗！"
          render("expends/new")
        end
      end

      def edit
        @expend = Expend.find(params[:id])
      end
    
      def update
        @expend = Expend.find(params[:id])
        if @expend.update(expend_params)
          flash[:notice] = "成功！"
          redirect_to("/expends/new")
        else
          flash.now[:alert] = "失敗！"
          render("expends/edit")
        end
      end

      def destroy
        @expend = Expend.find(params[:id])
        @expend.destroy
        flash[:notice] = "成功！"
        redirect_to("/expends/new")
      end

      def search
        if params[:id].empty?
          flash[:alert] = "検索失敗　※口座を選択してください"
          redirect_to("/incomes/new")
        elsif params[:expend_date].empty?
          flash[:alert] = "検索失敗　※項目を選択してください"
          redirect_to("/expends/new")
        else
        d = Date.parse(params[:expend_date])
        @expends = Expend.where(user_id:[current_user.id]).where(saving_id:params[:id]).where(expend_date: [d.beginning_of_month..d.end_of_month]).search(params[:expend_date]).reverse_order.paginate(page:params[:page], per_page: 10)
        @expend_month = Date.parse(params[:expend_date]).strftime("%-Y年%-m月")
        @expend = Expend.new
        @saving_name = "口座：" +Saving.where(id:params[:id]).pluck(:saving_name).join("")
        render("expends/new")
      end
    end

      private
        def expend_params
          params.require(:expend).permit(:saving_id, :user_id, :expend_date, :group, :expend_amount, :memo)
        end

       # def ensure_correct_user
        # @expend = Expend.find_by(id: params[:id])
        # if @expend.user_id != current_user.id
     #    flash[:alert] = "権限がありません"
      #   end
     #   end
        
end

app/helpers/expends_helper.rb
module ExpendsHelper
end

app/views/expends/edit.html.erb
<%= form_with(model: @expend, path:"/expends/:id") do |f| %>

    口座  <%= f.collection_select :saving_id,Saving.where(user_id:[current_user.id]),:id,:saving_name %><br>
    日付  <%= f.date_field :expend_date %><br>
    種別  <%= f.select :group, {'水道光熱費':'水道光熱費', '住居費':'住居費', '食費':'食費', '生活雑費':'生活雑費','交友費':'交友費','その他':'その他','不明':'不明' }%>　　　　　　 　 　　　 　　　　 <br>
    金額  <%= f.text_field :expend_amount %><br>
    メモ  <%= f.text_field :memo %><br>

  <%= f.submit "更新"%>
<% end %>

app/views/expends/new.html.erb
<div class="expend-title"><h1>支出管理</h1></div>
<br>
<%= image_tag 'money_saifu_kara_man.png',:size => '200x200' %>　
<h2>支出登録</h2>
<%= form_with(model: @expend, local:true) do |f| %>

    口座  <%= f.collection_select :saving_id,Saving.where(user_id:[current_user.id]),:id,:saving_name %><br>
    日付  <%= f.date_field :expend_date, value:Date.today %><br>
    種別  <%= f.select :group, {'水道光熱費':'水道光熱費', '住居費':'住居費', '食費':'食費', '生活雑費':'生活雑費','交友費':'交友費','その他':'その他','不明':'不明' }%>　　　　　　 　 　　　 　　　　 <br>
    金額  <%= f.text_field :expend_amount %><br>
    メモ  <%= f.text_field :memo %><br>

 　　 <%= f.submit "登録"%>
<% end %>

<hr>
<h2>支出履歴</h2>
 
   <div class="search-form">
     <%= form_with url: expends_search_path, method: :get, local: true do |f| %>
       <h4>口座 <%= f.collection_select :id, Saving.where(user_id:[current_user.id]), :id, :saving_name, prompt: "選択してください" %></h4>
       <h4>年月 <%= f.collection_select :expend_date ,Expend.where(user_id:[current_user.id]).group_by_month(:expend_date) ,:expend_date ,:expend_date_month ,prompt: "選択してください" %></h4>
      <%= f.submit "検索" %> 
     <% end %>
   </div>

<h2><%=@saving_name%>　<%= @expend_month %></h2>
<%= will_paginate %>
<br>
<table class="table">
<tr>
<th>口座名</th>
<th>日付</th>
<th>グループ</th>
<th>金額</th>
<th>メモ</th>
<th>編集 </th>
 <th>削除 </th>
</tr><tr>
  <% @expends.each do |expend| %>
    <% if expend.user_id == current_user.id %>
   
    <td> <%= Saving.where(id:expend.saving_id).pluck(:saving_name).join("")%> </td>
    <td> <%= expend.expend_date.strftime("%Y年%-m月%-d日") %> </td>
    <td> <%= expend.group%> </td>
    <td><div class="int">￥<%= expend.expend_amount.to_s(:delimited)%></div></td>
     <td><%= expend.memo %>
     <td><%= link_to("編集", "/expends/#{expend.id}/edit") %> </td>
     <td><%= link_to("削除", "/expends/#{expend.id}", method: :delete, data: {confirm: "本当に削除しますか？"}) %> </td>
 </tr>
    <% end %>
  <% end %>
</table>
<%= will_paginate %>