config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  get "/users/:id", to: "users#show"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  get "/savings/:id/index", to:"savings#index"
  resources :savings

  get '/incomes/search', to:"incomes#search"
  post '/incomes/search', to:"incomes#create"
  resources :incomes do
    collection {get "search"}
     resources :incomes, only: [ :new ]
   end

 #  get"/expends",          to:"expends#new"
 #  post "/expends",        to:"expends#create"
 #  get"/expends/new",      to:"expends#new"
 #  get "/expends/:id/edit",to:"expends#edit"
#   patch"/expends/:id",    to:"expends#update"
 #  put"/expends/:id",      to:"expends#update"
 #  delete"/expends/:id",   to:"expends#destroy"
   get '/expends/search',  to:"expends#search"
   post '/expends/search', to:"expends#create"
   resources :expends do
    collection {get "search"}
     resources :expends, only: [ :new ]
   end


 get "/analyses", to:"analyses#show"
 get '/analyses/search', to:"analyses#search"

end

app/controllers/analyses_controller.rb
class AnalysesController < ApplicationController
    before_action :authenticate_user!
    def show
     @income = Income.where(user_id:[current_user.id])
     @expends = Expend.where(user_id:[current_user.id])
     @expend = Expend.where(user_id:[current_user.id])
     @sum_of_expend = Expend.where(user_id:[current_user.id]).sum(:expend_amount).to_s(:delimited)
    # @saving_amount = Income.where(user_id:[current_user.id]).group_by_month(:income_date).sum(:income_amount) - Expend.where(user_id:[current_user.id]).group_by_month(:expend_date).sum(:expend_amount)
      # @arr_balence=Income.where(user_id:[current_user.id]).group_by_month(:income_date).sum(:income_amount).zip(Expend.where(user_id:[current_user.id]).group_by_month(:expend_date).sum(:expend_amount)).each do|inc,exp|
      # end
      income_hash = @income.group_by_month(:income_date).sum(:income_amount)
      expends_hash = @expends.group_by_month(:expend_date).sum(:expend_amount).transform_values { |v| v * -1 }
      @arr_balance = income_hash.merge(expends_hash) { |key, vi, ve| vi + ve }
     # @balance = @arr_balance.each_value{ |v|
     # v = @arr_balance.values.size.times.map{|i| @arr_balance.values[0..i].inject(:+)} }
      end

    def search
    if params[:expend_date].empty?
        flash[:alert] = "検索失敗　※項目を選択してください"
        redirect_to("/analyses")
      else
        @income = Income.where(user_id:[current_user.id]).where(saving_id:params[:id])
        @expends = Expend.where(user_id:[current_user.id]).where(saving_id:params[:id])
        d = Date.parse(params[:expend_date])
        @expend = Expend.where(user_id:[current_user.id]).where(expend_date: [d.beginning_of_month..d.end_of_month]).search(params[:expend_date]).where(saving_id:params[:id])
        @expend_month = Date.parse(params[:expend_date]).strftime("%-m月")
        if params[:id] 
          @saving_name = "口座名：" + Saving.where(id:params[:id]).pluck(:saving_name).join("")
        end
        @sum_of_expend = Expend.where(user_id:[current_user.id]).where(expend_date: [d.beginning_of_month..d.end_of_month]).search(params[:expend_date]).where(saving_id:params[:id]).sum(:expend_amount).to_s(:delimited)
        income_hash = @income.group_by_month(:income_date).order(income_date: :ASC).sum(:income_amount)
        expends_hash = @expends.group_by_month(:expend_date).order(expend_date: :ASC).sum(:expend_amount).transform_values { |v| v * -1 }
        @arr_balance = income_hash.merge(expends_hash){ |key, vi, ve| vi + ve }
        #@balance = @arr_balance.values.size.times.map{|i| @arr_balance.values[0..i].inject(:+)}
        render("analyses/show")
      end
end
end

app/helpers/analyses_helper.rb
module AnalysesHelper
end

app/views/analyses/show.html.erb
<div class="analyse-title"><h1>　分析　</h1></div>

<hr>
<%= image_tag 'kabu_chart_woman.png',:size => '200x200' %>　
<div class="search-form">
  <%= form_with url: analyses_search_path, method: :get, local: true do |f| %>
   <h4>口座選択 <%= f.collection_select :id,
     Saving.where(user_id:[current_user.id]), :id, :saving_name, include_blank: false %></h4>

   <h4>年月選択  <%= f.collection_select :expend_date,
    Expend.where(user_id:[current_user.id]).group_by_month(:expend_date), :expend_date, :expend_date_month, prompt: "選択してください" %></h4>

　　　<%= f.submit "表示" %> 
  <% end %>
</div>
<h1><%= @saving_name %></h1>
<h1><%= @expend_month %>  総支出額：￥<%= @sum_of_expend %></h1>
<h2><%= @expend_month %>支出内訳</h2>
<%= pie_chart @expend.group(:group).sum(:expend_amount) %>

<hr>
<div class="sav-hst"><h3>収支推移</h3></div>
 <%= column_chart  @arr_balance %>
※カーソルを乗せると月毎の合計金額が表示されます
<hr>
<div class="inc-hst"><h3>収入推移</h3></div>
<%= column_chart @income.group_by_month(:income_date).sum(:income_amount) %>
※カーソルを乗せると月毎の合計金額が表示されます
<hr>
<div class="exp-hst"><h3>支出推移</h3></div>
<%= column_chart @expends.group_by_month(:expend_date).sum(:expend_amount) %>
※カーソルを乗せると月毎の合計金額が表示されます