config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  get "/users/:id", to: "users#show"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  get "/savings/:id/index", to:"savings#index"
  resources :savings

  get '/incomes/search', to:"incomes#search"
  post '/incomes/search', to:"incomes#create"
  resources :incomes do
    collection {get "search"}
     resources :incomes, only: [ :new ]
   end

 #  get"/expends",          to:"expends#new"
 #  post "/expends",        to:"expends#create"
 #  get"/expends/new",      to:"expends#new"
 #  get "/expends/:id/edit",to:"expends#edit"
#   patch"/expends/:id",    to:"expends#update"
 #  put"/expends/:id",      to:"expends#update"
 #  delete"/expends/:id",   to:"expends#destroy"
   get '/expends/search',  to:"expends#search"
   post '/expends/search', to:"expends#create"
   resources :expends do
    collection {get "search"}
     resources :expends, only: [ :new ]
   end


 get "/analyses", to:"analyses#show"
 get '/analyses/search', to:"analyses#search"

end

app/models/income.rb
class Income < ApplicationRecord
    belongs_to :saving
    belongs_to :user

    validates :income_amount, presence: true, length: { maximum: 100 }
    validates :saving_id, presence: true
    validates :income_date, presence: true

    def self.search(income_date)
        where(["income_date", "%#{income_date}%"])
      end


    def income_date_month
        income_date.strftime("%Y年%-m月")
      end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

    def new
        @income = Income.new
        @incomes = Income.where(user_id:current_user.id).reverse_order.paginate(page:params[:page], per_page: 10)
        @income_month =nil
        @saving_name = "口座：" +Saving.where(id:params[:id]).pluck(:saving_name).join("")
    end

    def create
        @income = Income.new(income_params)
        @income.user_id = current_user.id
        if @income.save
            flash[:notice] = "成功　#{Income.where(user_id:current_user.id).pluck(:income_date).last.strftime("%Y年%-m月%-d日")}　￥#{Income.where(user_id:current_user.id).pluck(:income_amount).last}　メモ：#{Income.where(user_id:current_user.id).pluck(:memo).last}"
          redirect_to("/incomes/new")
        else
            flash.now[:alert] = "失敗！"
            @incomes = Income.where(user_id:current_user.id).paginate(page:params[:page], per_page: 10)
          render("incomes/new")
        end
      end

      def edit
        @income = Income.find(params[:id])
      end
    
      def update
        @income = Income.find(params[:id])
        if @income.update(income_params)
          flash[:notice] = "成功！"
          redirect_to("/incomes/new")
        else
          flash.now[:alert] = "失敗！"
          render("incomes/edit")
        end
      end

      def destroy
        @income = Income.find(params[:id])
        @income.destroy
        flash[:notice] = "成功！"
        redirect_to("/incomes/new")
      end

      def search
        if params[:id].empty?
        flash[:alert] = "検索失敗　※口座を選択してください"
        redirect_to("/incomes/new")
      elsif params[:income_date].empty?
          flash[:alert] = "検索失敗　※年月を選択してください"
          redirect_to("/incomes/new")
        else
          d = Date.parse(params[:income_date])
          @incomes = Income.where(user_id:[current_user.id]).where(income_date: [d.beginning_of_month..d.end_of_month]).where(saving_id:params[:id]).search(params[:income_date]).reverse_order.paginate(page:params[:page], per_page: 10)
          @income_month = Date.parse(params[:income_date]).strftime("%-Y年%-m月")
          @income = Income.new
          @saving_name = "口座：" + Saving.where(id:params[:id]).pluck(:saving_name).join("")
          render("incomes/new")
        end
      end

      private
        def income_params
          params.require(:income).permit(:saving_id, :user_id, :income_date, :income_amount, :memo)
        end

end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/incomes/edit.html.erb
<%= form_with(model: @income, path:"/incomes/:id") do |f| %>

   口座  <%= f.collection_select :saving_id,Saving.where(user_id:[current_user.id]),:id,:saving_name  %><br>
   日付  <%= f.date_field :income_date %><br>
   金額  <%= f.text_field :income_amount %><br>
   メモ  <%= f.text_field :memo %><br>

  <%= f.submit "更新"%>
<% end %>

app/views/incomes/new.html.erb
<div class="income-title"><h1>収入管理</h1></div>
<%= image_tag 'kyuryou_bonus_woman2.png',:size => '200x200' %>　

<h2>収入登録</h2>
<%= form_with(model: @income, local: true) do |f| %>

   口座  <%= f.collection_select :saving_id,Saving.where(user_id:[current_user.id]),:id,:saving_name  %><br>
   日付  <%= f.date_field :income_date , value:Date.today%><br>
   金額  <%= f.text_field :income_amount %><br>
   メモ  <%= f.text_field :memo %><br>

  　 　<%= f.submit "登録"%>
<% end %>


<hr>
<h2>収入履歴</h2>

<div class="search-form">
  <%= form_with url: incomes_search_path, method: :get, local: true do |f| %>
   <h4>口座 <%= f.collection_select :id, Saving.where(user_id:[current_user.id]), :id, :saving_name , prompt: "選択してください"%></h4>
   <h4>年月 <%= f.collection_select :income_date, Income.where(user_id:[current_user.id]).group_by_month(:income_date), :income_date, :income_date_month , prompt: "選択してください"%></h4>
 　　　<%= f.submit "検索" %> 
  <% end %>
</div>
<h2><%=@saving_name%>　<%= @income_month %></h2>

<%= will_paginate %>
<br>
<table class="table">
  <tr>
    <th>口座名</th>
    <th>日付 </th>
    <th>金額</th>
    <th>メモ </th>
    <th>編集 </th>
    <th>削除 </th></tr>
      <tr>
   <% @incomes.each do |income| %>
     <% if income.user_id == current_user.id %>
      <td><%= Saving.where(id:income.saving_id).pluck(:saving_name).join("")%></td>
      <td><%= income.income_date.strftime("%Y年%-m月%-d日") %></td>
      <td><div class="int">￥<%= income.income_amount.to_s(:delimited) %></div></td>
      <td><%= income.memo %></td>
      <td><%= link_to("編集", "/incomes/#{income.id}/edit") %></td>
      <td><%= link_to("削除", "/incomes/#{income.id}", method: :delete, data: {confirm: "本当に削除しますか？"}) %></td>
      </tr>
     <% end %>
   <% end %>
 </table>

<%= will_paginate %>